# https://github.com/elastic/kibana-docker
FROM docker.elastic.co/kibana/kibana:5.2.2

# Add your kibana plugins setup here
# Example: RUN kibana-plugin install <name|url>
RUN kibana-plugin install https://github.com/floragunncom/search-guard-kibana-plugin/releases/download/v5.2.2-1/searchguard-kibana-5.2.2-1.zip
