---
## Default Kibana configuration from Kibana base image.
## https://github.com/elastic/kibana/blob/main/src/dev/build/tasks/os_packages/docker_generator/templates/kibana_yml.template.ts
#
server.name: kibana
server.host: 0.0.0.0
elasticsearch.hosts: [ http://elasticsearch:9200 ]

monitoring.ui.container.elasticsearch.enabled: true
monitoring.ui.container.logstash.enabled: true

## Security credentials
#
elasticsearch.username: kibana_system
elasticsearch.password: ${KIBANA_SYSTEM_PASSWORD}

## Encryption keys (optional but highly recommended)
##
## Generate with either
##  $ docker compose up kibana-genkeys
##  $ openssl rand -hex 32
##
## https://www.elastic.co/docs/deploy-manage/security/self-setup
## https://www.elastic.co/docs/reference/kibana/commands/kibana-encryption-keys
#
xpack.security.encryptionKey: a07c6c51c538b710acb45667f3fb7b2c237061c8665bf7917109a6360b70af84
xpack.encryptedSavedObjects.encryptionKey: d8fa931e7e596b2333094dd6a0e9c36fe22a27a0d522cb3c2c5cc3033fe4ae3a
xpack.reporting.encryptionKey: e5cf136d7caf4c15c0b82893ef588359684c3dc5e51e4eaa80fc2c4c455db64b
