# Disable noisy internal loggers
logger.instrument.name = logstash.instrument
logger.instrument.level = info

logger.periodicflush.name = org.logstash.execution.PeriodicFlush
logger.periodicflush.level = info

logger.jvm.name = logstash.instrument.periodicpoller.jvm
logger.jvm.level = info

logger.cgroup.name = logstash.instrument.periodicpoller.cgroup
logger.cgroup.level = info

logger.secinstr.name = org.logstash.instrument
logger.secinstr.level = info

logger.runner.name = logstash.runner
logger.runner.level = info

logger.conf.name =  logstash.config.source.local.configpathloader
logger.conf.level = info

logger.agent.name = logstash.agent
logger.agent.level = info

status = error
name = LogstashPropertiesConfig

appender.console.type = Console
appender.console.name = plain_console
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = [%d{ISO8601}][%-5p][%-25c]%notEmpty{[%X{pipeline.id}]}%notEmpty{[%X{plugin.id}]} %m%n

appender.json_console.type = Console
appender.json_console.name = json_console
appender.json_console.layout.type = JSONLayout
appender.json_console.layout.compact = true
appender.json_console.layout.eventEol = true

rootLogger.level = ${sys:ls.log.level}
rootLogger.appenderRef.console.ref = ${sys:ls.log.format}_console
