ARG ELASTIC_VERSION

# https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash:${ELASTIC_VERSION:-9.1.3}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
