ARG ELK_VERSION
ARG ELK_FLAVOUR

# https://github.com/elastic/logstash-docker / https://www.docker.elastic.co/
FROM docker.elastic.co/logstash/logstash${ELK_FLAVOUR}:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json
